"""empty message

Revision ID: 095da3084876
Revises: e89b7f3854c7
Create Date: 2023-03-01 09:19:35.331440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095da3084876'
down_revision = 'e89b7f3854c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

