"""empty message

Revision ID: e89b7f3854c7
Revises: 8b8e201390e8
Create Date: 2023-03-01 00:40:58.421202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89b7f3854c7'
down_revision = '8b8e201390e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emailcredentials', sa.Column('imap_server', sa.String(length=50), nullable=True))
    op.add_column('emailcredentials', sa.Column('pop_port', sa.Integer(), nullable=True))
    op.add_column('emailcredentials', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('emailcredentials', sa.Column('imap_port', sa.Integer(), nullable=True))
    op.alter_column('emailcredentials', 'pop_server',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('emailcredentials', 'smtp_server',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emailcredentials', 'smtp_server',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('emailcredentials', 'pop_server',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('emailcredentials', 'imap_port')
    op.drop_column('emailcredentials', 'smtp_port')
    op.drop_column('emailcredentials', 'pop_port')
    op.drop_column('emailcredentials', 'imap_server')
    # ### end Alembic commands ###

